---
driver:
  name: vagrant
  forward_agent: true
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo
  require_chef_omnibus: '11.10.4'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: 
      - recipe[lvsf-opsworks-php-cookbook::default]
      - recipe[test-helper::default]
      # - recipe[lvsf-opsworks-php-cookbook::deploy_local]
    attributes:
      deploy_local:
        lvsf_php_services:
          git_url: ''
          git_rev: 'master'
