---
driver:
  name: vagrant
  forward_agent: true
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: 
      - recipe[php5-fpm::install]
      - recipe[php5-fpm::create_user]
      - recipe[php5-fpm::configure_pools]
      - recipe[php5-fpm::configure_fpm]
      - recipe[lvsf-opsworks-php-cookbook::default]
    attributes:
